// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6OlEtHC9rXFE9WoU99FxywL5yITASGOA',
    appId: '1:854370715125:web:96f4527c6ee57df2924cbc',
    messagingSenderId: '854370715125',
    projectId: 'seiyun-university-system',
    authDomain: 'seiyun-university-system.firebaseapp.com',
    storageBucket: 'seiyun-university-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtAzoIxhvL_Dj0e1prBDzQJt3ILa3XxsA',
    appId: '1:854370715125:android:534b1294a2f30642924cbc',
    messagingSenderId: '854370715125',
    projectId: 'seiyun-university-system',
    storageBucket: 'seiyun-university-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGOyoUHbuA4FJ51PVdvQT-XPLNgPPbsnI',
    appId: '1:854370715125:ios:da32a1ca0943d2c0924cbc',
    messagingSenderId: '854370715125',
    projectId: 'seiyun-university-system',
    storageBucket: 'seiyun-university-system.firebasestorage.app',
    iosBundleId: 'com.example.seiyunCorrespondence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGOyoUHbuA4FJ51PVdvQT-XPLNgPPbsnI',
    appId: '1:854370715125:ios:da32a1ca0943d2c0924cbc',
    messagingSenderId: '854370715125',
    projectId: 'seiyun-university-system',
    storageBucket: 'seiyun-university-system.firebasestorage.app',
    iosBundleId: 'com.example.seiyunCorrespondence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6OlEtHC9rXFE9WoU99FxywL5yITASGOA',
    appId: '1:854370715125:web:dd39fc40bf7c2b1b924cbc',
    messagingSenderId: '854370715125',
    projectId: 'seiyun-university-system',
    authDomain: 'seiyun-university-system.firebaseapp.com',
    storageBucket: 'seiyun-university-system.firebasestorage.app',
  );

}